spring.application.name=crud-primefaces

# Configurazione JSF / PrimeFaces
spring.mvc.view.prefix=/
spring.mvc.view.suffix=.xhtml
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# Imposta la pagina iniziale (non c'e login)
spring.mvc.welcome-page-location=classpath:/templates/index.xhtml

# Configurazione del database H2 in memoria
spring.datasource.url=jdbc:h2:mem:esamedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Permette a JPA di creare/aggiornare automaticamente le tabelle nel DB in base alle tue classi Java
spring.jpa.hibernate.ddl-auto=update
# Mostra le query SQL nel terminale (molto utile per il debug)
spring.jpa.show-sql=true

# Abilita la console web di H2 per vedere il database (raggiungibile a http://localhost:8080/h2-console)
spring.h2.console.enabled=true

